name: '/dev/random'
description: 'Random thoughts on development and stuff'
author: Hans Kristian Flaatten
url: http://starefossen.github.io
repo: https://github.com/starefossen/starefossen.github.com
ga_id: UA-38558206-2

social: !!omap
  - icon: twitter
    url: https://twitter.com/starefossen
  - icon: github
    url: https://github.com/starefossen
  - icon: linkedin
    url: https://linkedin.com/hans.flaatten

relative_permalinks: false
permalink: /post/:year/:month/:day/:title/
excerpt_separator: <!--more-->
markdown: redcarpet
highlighter: pygments
timezone: NO
encoding: UTF-8

safe: true

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

