name: '/dev/random'
description: 'Random thoughts on development and stuff'
author: Hans Kristian Flaatten
url: http://starefossen.github.io
repo: https://github.com/starefossen/starefossen.github.com
ga_id: UA-38558206-2

social: !!omap
  - img: twtter.png
    cls: twtter
    url: https://twitter.com/starefossen
  - img: github.png
    cls: github
    url: https://github.com/starefossen
  - img: lnkedin.png
    cls: lnkedin
    url: https://linkedin.com/hans.flaatten

relative_permalinks: false
permalink: /post/:year/:month/:day/:title/
excerpt_separator: <!--more-->
markdown: redcarpet
highlighter: true
timezone: NO
encoding: UTF-8

safe: true

