name: '/dev/random'
description: 'Random thoughts on development and stuff'
author:
    name: Hans Kristian Flaatten
    email: hans@starefossen.com
url: https://starefossen.github.io

ga_id: UA-38558206-2

license:
    title: Creative Commons CC BY-SA 4.0 license
    url: https://creativecommons.org/licenses/by-sa/4.0/

social: !!omap
  - icon: twitter
    url: https://twitter.com/starefossen
  - icon: github
    url: https://github.com/starefossen
  - icon: linkedin
    url: https://linkedin.com/hans.flaatten

relative_permalinks: false
permalink: /post/:year/:month/:day/:title/
excerpt_separator: <!--more-->
markdown: redcarpet
highlighter: pygments
timezone: NO
encoding: UTF-8

repository: Starefossen/starefossen.github.com

gems:
- jekyll-feed
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
